apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: vector-postgres
spec:
  instances: 3
  imageName: ghcr.io/singularity-ng/centralcloud-postgres:18-cnpg-ext
  postgresql:
    shared_preload_libraries:
      - vchord
      - vchord_bm25
      - pg_tokenizer
    parameters:
      pg_stat_statements.track: all
  bootstrap:
    initdb:
      postInitSQL:
        - CREATE EXTENSION IF NOT EXISTS vector;
        - CREATE EXTENSION IF NOT EXISTS vchord;
        - CREATE EXTENSION IF NOT EXISTS pg_tokenizer;
        - CREATE EXTENSION IF NOT EXISTS vchord_bm25 CASCADE;
        - CREATE EXTENSION IF NOT EXISTS pg_stat_statements;
  storage:
    size: 100Gi

